$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

display_name: federated_learning_pipeline
description: Federated learning pipeline

inputs:
  train_model:
    path: ./dummy_model
    type: custom_model

jobs:
  loop_body:
    type: pipeline
    component: ./components/federated_learning_pipeline_component.yml
    inputs:
      input_model: ${{parent.inputs.train_model}}

  federated_learning_dowhile_node:
    type: do_while
    body: ${{parent.jobs.loop_body}}
    limits:
      max_iteration_count: 5
    condition: ${{parent.jobs.loop_body.outputs.condition_output}}
    mapping:
      agg_output: input_model

  aggregate_node:
    type: command
    component: ./components/aggregate_train/component.yml
    inputs:
      model_1: ${{parent.jobs.loop_body.outputs.agg_output}}
      model_2: ${{parent.jobs.loop_body.outputs.agg_output}}