$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline

display_name: federated_learning_body
description: Body of each iteration of federated learning, include multi silos and aggregate node

inputs:
  input_model:
    type: uri_folder

outputs:
  agg_output:
    type: uri_folder
  condition_output:
    type: boolean
    is_control: true

jobs:
  silo_1:
    type: pipeline
    component: ./silo_pipeline_component.yml
    inputs:
      input_model: ${{parent.inputs.input_model}}

  silo_2:
    type: pipeline
    component: ./silo_pipeline_component.yml
    inputs:
      input_model: ${{parent.inputs.input_model}}

  aggregate_node:
    type: command
    component: ./aggregate_train/component.yml
    inputs:
      model_1: ${{parent.jobs.silo_1.outputs.output_model}}
      model_2: ${{parent.jobs.silo_2.outputs.output_model}}
    outputs:
      agg_output: ${{parent.outputs.agg_output}}
      output: ${{parent.outputs.condition_output}}